## 教師あり学習の際、データ分類を行うための方法

### 二値化
**値を2.1を閾値にして0 or 1で正規化する**

In [1]:
import numpy as np
from sklearn import preprocessing

input_data = np.array([[5.1, -2.9, 3.3],
                     [-1.2, 7.8, -6.1],
                     [3.9, 0.4, 2.1],
                     [7.3, -9.9, -4.5]])

data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("Binarized data:\n", data_binarized)

Binarized data:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


### 平均値を引く

値から平均値を引くと、特徴量の中心が原点になり平均からの偏りを表すことができる

In [2]:
print("BEFORE:")
print("Mean（平均）=", input_data.mean(axis=0))
print("Std deviation（標準偏差）=", input_data.std(axis=0))

BEFORE:
Mean（平均）= [ 3.775 -1.15  -1.3  ]
Std deviation（標準偏差）= [3.12039661 6.36651396 4.0620192 ]


In [4]:
data_scaled = preprocessing.scale(input_data)
print("AFTER:")
print("Mean（平均）=", data_scaled.mean(axis=0))
print("Std deviation（標準偏差）=", data_scaled.std(axis=0))

AFTER:
Mean（平均）= [1.11022302e-16 0.00000000e+00 2.77555756e-17]
Std deviation（標準偏差）= [1. 1. 1.]
